" Load pathogen
execute pathogen#infect()

syntax enable

" Colorscheme options
let g:gruvbox_contrast_dark='hard'
let g:gruvbox_contrast_light='hard'
set background=light
set termguicolors
colorscheme default " use onedark for dark version


" Enable python syntax highlighting
let python_highlight_all = 1

" YouCompleteMe config
" Disable identifier completer (popup as you type)
let g:ycm_min_num_of_chars_for_completion=3
" Add tex to the default ycm blacklist
let g:ycm_filetype_blacklist = {
        \ 'tagbar' : 1,
        \ 'qf' : 1,
        \ 'notes' : 1,
        \ 'markdown' : 1,
        \ 'unite' : 1,
        \ 'text' : 1,
        \ 'vimwiki' : 1,
        \ 'pandoc' : 1,
        \ 'infolog' : 1,
        \ 'tex' : 1,
        \ 'mail' : 1,
        \}

" CommandT config
" Use `git ls-files` for finding files. Consequently git-ignored files won't appear in the hitlist.
let g:CommandTFileScanner = "git"
" Map <C-b> to open hit in horizontal split. <C-s> suspends terminal.
map <C-b> <C-s>
" Enable <ESC> for closing the cmd-T buffer (taken from official help)
if &term =~ "xterm" || &term =~ "screen"
  let g:CommandTCancelMap = ['<ESC>', '<C-c>']
 endif

" Filebrowsing (netrw) config
let g:netrw_banner=0        " disable annoying banner
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()

set laststatus=2  " Always display statusbar (ie. powerline)
set cursorline  " Highlight line where cursor currently is


" Custom keybinding
command! ClearQuickfixList cexpr []
imap <F8> <ESC><F8>
cmap <F8> <ESC><F8>
" Shortcut for writting in all (changed) buffers and building on all cores.
" Recall that make! (in contrast to make) will not jump to first quickfix error.
nmap <F8> :wa<CR>:make! -j$(grep -c ^processor /proc/cpuinfo)<CR>
" Moving between tabs
nmap <F5> :tabprevious<CR>
nmap <F6> :tabnext<CR>

set nocompatible  " Don't pretend to be vi
set splitright  " Create vsp buffers to the right
set splitbelow  " Create sp buffers to the bottom
set nofoldenable
set number  " Enable line numbers
set sts=3
filetype on
filetype indent on
set et
set sw=3
set hls
"set fo=qrotcnl1
set bs=indent,eol,start
set list

if v:version >= 700
   set lcs=trail:·,precedes:«,extends:»,nbsp:◊,tab:»·
else
   set listchars=tab:>-,trail:-
endif

autocmd FileType c call MyC()
autocmd FileType cpp call MyC()

" TODO: some shortcut for :noh<CR> to disable search highlighting
map  <Up>        gk
imap <Up>   <C-O>gk
map  <Down>      gj
imap <Down> <C-O>gj

function! MyC()
   set cindent
   set cino=(0,W1s,m1
endfunction

set expandtab       "Use softtabstop spaces instead of tab characters for indentation
set shiftwidth=3    "Indent by 4 spaces when using >>, <<, == etc.
set softtabstop=3   "Indent by 4 spaces when pressing <TAB>

set autoindent      "Keep indentation from previous line
set smartindent     "Automatically inserts indentation in some cases
set cindent         "Like smartindent, but stricter and more customisable

autocmd Filetype gitcommit setlocal textwidth=72
autocmd Filetype python setlocal shiftwidth=4 softtabstop=4 tabstop=8
autocmd Filetype tex setlocal shiftwidth=1 softtabstop=1 tabstop=8
autocmd FileType make setlocal noexpandtab shiftwidth=8 softtabstop=0

function! StripTrailingWhitespace()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

augroup clear_trailing_whitespace
   " Remove previously defined autocmds in this group
   autocmd!
   " Clear trailing whitespace
   autocmd BufWritePre * :call StripTrailingWhitespace()
augroup END
" Clear clear_trailing_whitespace group, for certain files
autocmd FileType diff autocmd! clear_trailing_whitespace
set colorcolumn=121  "Highlight column 121 which is OOB.

function! TextModeConfig()
  if exists("b:textmodeenabled") && b:textmodeenabled==1
    let b:textmodeenabled=0
    set nospell
    call youcompleteme#EnableCursorMovedAutocommands()
  else
    let b:textmodeenabled=1
    set spell  " enable spellchecking
    call youcompleteme#DisableCursorMovedAutocommands()  " Disable YouCompleteMe
  endif
endfunction
command! TextMode :call TextModeConfig()

